//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3082.
// 
#pragma warning disable 1591

namespace PakTurk_school_system.ViewMarksWS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ViewMarksWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class ViewMarksWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMarks4StudentsBLLOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMarks4TeachersBLLOperationCompleted;
        
        private System.Threading.SendOrPostCallback enterStudentMarksBLLOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveStudentMarksBLLOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ViewMarksWebService() {
            this.Url = global::PakTurk_school_system.Properties.Settings.Default.PakTurk_school_system_ViewMarksWS_ViewMarksWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event getMarks4StudentsBLLCompletedEventHandler getMarks4StudentsBLLCompleted;
        
        /// <remarks/>
        public event getMarks4TeachersBLLCompletedEventHandler getMarks4TeachersBLLCompleted;
        
        /// <remarks/>
        public event enterStudentMarksBLLCompletedEventHandler enterStudentMarksBLLCompleted;
        
        /// <remarks/>
        public event SaveStudentMarksBLLCompletedEventHandler SaveStudentMarksBLLCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getMarks4StudentsBLL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getMarks4StudentsBLL(string rollNo) {
            object[] results = this.Invoke("getMarks4StudentsBLL", new object[] {
                        rollNo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getMarks4StudentsBLLAsync(string rollNo) {
            this.getMarks4StudentsBLLAsync(rollNo, null);
        }
        
        /// <remarks/>
        public void getMarks4StudentsBLLAsync(string rollNo, object userState) {
            if ((this.getMarks4StudentsBLLOperationCompleted == null)) {
                this.getMarks4StudentsBLLOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMarks4StudentsBLLOperationCompleted);
            }
            this.InvokeAsync("getMarks4StudentsBLL", new object[] {
                        rollNo}, this.getMarks4StudentsBLLOperationCompleted, userState);
        }
        
        private void OngetMarks4StudentsBLLOperationCompleted(object arg) {
            if ((this.getMarks4StudentsBLLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMarks4StudentsBLLCompleted(this, new getMarks4StudentsBLLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getMarks4TeachersBLL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getMarks4TeachersBLL(string userName, string className, string subjectName, ref System.Data.DataSet res) {
            object[] results = this.Invoke("getMarks4TeachersBLL", new object[] {
                        userName,
                        className,
                        subjectName,
                        res});
            res = ((System.Data.DataSet)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getMarks4TeachersBLLAsync(string userName, string className, string subjectName, System.Data.DataSet res) {
            this.getMarks4TeachersBLLAsync(userName, className, subjectName, res, null);
        }
        
        /// <remarks/>
        public void getMarks4TeachersBLLAsync(string userName, string className, string subjectName, System.Data.DataSet res, object userState) {
            if ((this.getMarks4TeachersBLLOperationCompleted == null)) {
                this.getMarks4TeachersBLLOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMarks4TeachersBLLOperationCompleted);
            }
            this.InvokeAsync("getMarks4TeachersBLL", new object[] {
                        userName,
                        className,
                        subjectName,
                        res}, this.getMarks4TeachersBLLOperationCompleted, userState);
        }
        
        private void OngetMarks4TeachersBLLOperationCompleted(object arg) {
            if ((this.getMarks4TeachersBLLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMarks4TeachersBLLCompleted(this, new getMarks4TeachersBLLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/enterStudentMarksBLL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string enterStudentMarksBLL(string userName, string className, string subjectName, ref System.Data.DataSet res) {
            object[] results = this.Invoke("enterStudentMarksBLL", new object[] {
                        userName,
                        className,
                        subjectName,
                        res});
            res = ((System.Data.DataSet)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void enterStudentMarksBLLAsync(string userName, string className, string subjectName, System.Data.DataSet res) {
            this.enterStudentMarksBLLAsync(userName, className, subjectName, res, null);
        }
        
        /// <remarks/>
        public void enterStudentMarksBLLAsync(string userName, string className, string subjectName, System.Data.DataSet res, object userState) {
            if ((this.enterStudentMarksBLLOperationCompleted == null)) {
                this.enterStudentMarksBLLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnenterStudentMarksBLLOperationCompleted);
            }
            this.InvokeAsync("enterStudentMarksBLL", new object[] {
                        userName,
                        className,
                        subjectName,
                        res}, this.enterStudentMarksBLLOperationCompleted, userState);
        }
        
        private void OnenterStudentMarksBLLOperationCompleted(object arg) {
            if ((this.enterStudentMarksBLLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.enterStudentMarksBLLCompleted(this, new enterStudentMarksBLLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveStudentMarksBLL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SaveStudentMarksBLL(string userName, string className, string subjectName, ref System.Data.DataSet res) {
            object[] results = this.Invoke("SaveStudentMarksBLL", new object[] {
                        userName,
                        className,
                        subjectName,
                        res});
            res = ((System.Data.DataSet)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SaveStudentMarksBLLAsync(string userName, string className, string subjectName, System.Data.DataSet res) {
            this.SaveStudentMarksBLLAsync(userName, className, subjectName, res, null);
        }
        
        /// <remarks/>
        public void SaveStudentMarksBLLAsync(string userName, string className, string subjectName, System.Data.DataSet res, object userState) {
            if ((this.SaveStudentMarksBLLOperationCompleted == null)) {
                this.SaveStudentMarksBLLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveStudentMarksBLLOperationCompleted);
            }
            this.InvokeAsync("SaveStudentMarksBLL", new object[] {
                        userName,
                        className,
                        subjectName,
                        res}, this.SaveStudentMarksBLLOperationCompleted, userState);
        }
        
        private void OnSaveStudentMarksBLLOperationCompleted(object arg) {
            if ((this.SaveStudentMarksBLLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveStudentMarksBLLCompleted(this, new SaveStudentMarksBLLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void getMarks4StudentsBLLCompletedEventHandler(object sender, getMarks4StudentsBLLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMarks4StudentsBLLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMarks4StudentsBLLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void getMarks4TeachersBLLCompletedEventHandler(object sender, getMarks4TeachersBLLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMarks4TeachersBLLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMarks4TeachersBLLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet res {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void enterStudentMarksBLLCompletedEventHandler(object sender, enterStudentMarksBLLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enterStudentMarksBLLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal enterStudentMarksBLLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet res {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void SaveStudentMarksBLLCompletedEventHandler(object sender, SaveStudentMarksBLLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveStudentMarksBLLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveStudentMarksBLLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet res {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591