//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3082.
// 
#pragma warning disable 1591

namespace PakTurk_school_system.assignSubjectService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="manageTeacherSoap", Namespace="http://tempuri.org/")]
    public partial class manageTeacher : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback assignSubjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback makeClassInchargeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTeacherDetailsBLLOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public manageTeacher() {
            this.Url = global::PakTurk_school_system.Properties.Settings.Default.PakTurk_school_system_assignSubjectService_manageTeacher;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event assignSubjectCompletedEventHandler assignSubjectCompleted;
        
        /// <remarks/>
        public event makeClassInchargeCompletedEventHandler makeClassInchargeCompleted;
        
        /// <remarks/>
        public event getTeacherDetailsBLLCompletedEventHandler getTeacherDetailsBLLCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/assignSubject", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool assignSubject(string teacher, string ClsName, string subject, string subjectType, string classsection) {
            object[] results = this.Invoke("assignSubject", new object[] {
                        teacher,
                        ClsName,
                        subject,
                        subjectType,
                        classsection});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void assignSubjectAsync(string teacher, string ClsName, string subject, string subjectType, string classsection) {
            this.assignSubjectAsync(teacher, ClsName, subject, subjectType, classsection, null);
        }
        
        /// <remarks/>
        public void assignSubjectAsync(string teacher, string ClsName, string subject, string subjectType, string classsection, object userState) {
            if ((this.assignSubjectOperationCompleted == null)) {
                this.assignSubjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnassignSubjectOperationCompleted);
            }
            this.InvokeAsync("assignSubject", new object[] {
                        teacher,
                        ClsName,
                        subject,
                        subjectType,
                        classsection}, this.assignSubjectOperationCompleted, userState);
        }
        
        private void OnassignSubjectOperationCompleted(object arg) {
            if ((this.assignSubjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.assignSubjectCompleted(this, new assignSubjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/makeClassIncharge", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool makeClassIncharge(string cls, string inch) {
            object[] results = this.Invoke("makeClassIncharge", new object[] {
                        cls,
                        inch});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void makeClassInchargeAsync(string cls, string inch) {
            this.makeClassInchargeAsync(cls, inch, null);
        }
        
        /// <remarks/>
        public void makeClassInchargeAsync(string cls, string inch, object userState) {
            if ((this.makeClassInchargeOperationCompleted == null)) {
                this.makeClassInchargeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmakeClassInchargeOperationCompleted);
            }
            this.InvokeAsync("makeClassIncharge", new object[] {
                        cls,
                        inch}, this.makeClassInchargeOperationCompleted, userState);
        }
        
        private void OnmakeClassInchargeOperationCompleted(object arg) {
            if ((this.makeClassInchargeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.makeClassInchargeCompleted(this, new makeClassInchargeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getTeacherDetailsBLL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getTeacherDetailsBLL(string tName) {
            object[] results = this.Invoke("getTeacherDetailsBLL", new object[] {
                        tName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getTeacherDetailsBLLAsync(string tName) {
            this.getTeacherDetailsBLLAsync(tName, null);
        }
        
        /// <remarks/>
        public void getTeacherDetailsBLLAsync(string tName, object userState) {
            if ((this.getTeacherDetailsBLLOperationCompleted == null)) {
                this.getTeacherDetailsBLLOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTeacherDetailsBLLOperationCompleted);
            }
            this.InvokeAsync("getTeacherDetailsBLL", new object[] {
                        tName}, this.getTeacherDetailsBLLOperationCompleted, userState);
        }
        
        private void OngetTeacherDetailsBLLOperationCompleted(object arg) {
            if ((this.getTeacherDetailsBLLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTeacherDetailsBLLCompleted(this, new getTeacherDetailsBLLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void assignSubjectCompletedEventHandler(object sender, assignSubjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class assignSubjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal assignSubjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void makeClassInchargeCompletedEventHandler(object sender, makeClassInchargeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class makeClassInchargeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal makeClassInchargeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void getTeacherDetailsBLLCompletedEventHandler(object sender, getTeacherDetailsBLLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTeacherDetailsBLLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTeacherDetailsBLLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591