//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PakTurk_school_system.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:30570/PakTurkBLL/RegistrationService.asmx")]
        public string PakTurk_school_system_localhost1_RegistrationService {
            get {
                return ((string)(this["PakTurk_school_system_localhost1_RegistrationService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=GULSOFTE-9D6F32\\SQLEXPRESS;Initial Catalog=School_System;Integrated S" +
            "ecurity=True")]
        public string School_SystemConnectionString {
            get {
                return ((string)(this["School_SystemConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:30570/PakTurkBLL/SearchRegisteredStudent.asmx")]
        public string PakTurk_school_system_searchStudent_SearchRegisteredStudent {
            get {
                return ((string)(this["PakTurk_school_system_searchStudent_SearchRegisteredStudent"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:30570/PakTurkBLL/AdmitStudent.asmx")]
        public string PakTurk_school_system_AdmintTheStudent_AdmitStudent {
            get {
                return ((string)(this["PakTurk_school_system_AdmintTheStudent_AdmitStudent"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:30570/PakTurkBLL/CreateUserWebService.asmx")]
        public string PakTurk_school_system_creatUser_CreateUserWebService {
            get {
                return ((string)(this["PakTurk_school_system_creatUser_CreateUserWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:30570/PakTurkBLL/LoginWebService.asmx")]
        public string PakTurk_school_system_UserAuthenticate_LoginWebService {
            get {
                return ((string)(this["PakTurk_school_system_UserAuthenticate_LoginWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:30570/PakTurkBLL/ManageCoursesWebService.asmx")]
        public string PakTurk_school_system_ManageCourseWS_ManageCoursesWebService {
            get {
                return ((string)(this["PakTurk_school_system_ManageCourseWS_ManageCoursesWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:30570/PakTurkBLL/ChangePasswordWebService.asmx")]
        public string PakTurk_school_system_ChangePassword_ChangePasswordWebService {
            get {
                return ((string)(this["PakTurk_school_system_ChangePassword_ChangePasswordWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BUTT-94DC6D2530\\SQLEXPRESS;Initial Catalog=School_System;Integrated S" +
            "ecurity=True")]
        public string School_SystemConnectionString1 {
            get {
                return ((string)(this["School_SystemConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:30570/PakTurkBLL/manageTeacher.asmx")]
        public string PakTurk_school_system_assignSubjectService_manageTeacher {
            get {
                return ((string)(this["PakTurk_school_system_assignSubjectService_manageTeacher"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:30570/PakTurkBLL/AttendanceWebService.asmx")]
        public string PakTurk_school_system_AttendanceWS_AttendanceWebService {
            get {
                return ((string)(this["PakTurk_school_system_AttendanceWS_AttendanceWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:30570/PakTurkBLL/ViewMarksWebService.asmx")]
        public string PakTurk_school_system_ViewMarksWS_ViewMarksWebService {
            get {
                return ((string)(this["PakTurk_school_system_ViewMarksWS_ViewMarksWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:30570/PakTurkBLL/manageClass.asmx")]
        public string PakTurk_school_system_ManageclsService_manageClass {
            get {
                return ((string)(this["PakTurk_school_system_ManageclsService_manageClass"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:30570/PakTurkBLL/UpadateUser.asmx")]
        public string PakTurk_school_system_UpdateUserInfo_UpadateUser {
            get {
                return ((string)(this["PakTurk_school_system_UpdateUserInfo_UpadateUser"]));
            }
        }
    }
}
