//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3082.
// 
#pragma warning disable 1591

namespace PakTurk_school_system.creatUser {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CreateUserWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class CreateUserWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Create_User_LoginOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CreateUserWebService() {
            this.Url = global::PakTurk_school_system.Properties.Settings.Default.PakTurk_school_system_creatUser_CreateUserWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Create_User_LoginCompletedEventHandler Create_User_LoginCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Create_User_Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Create_User_Login(string txtFName, string txtLName, string txtPhoneNo, string txtMobileNo, string txtEMail, string txtAddress, string txtUsername, string txtCountry, string comboUserType) {
            object[] results = this.Invoke("Create_User_Login", new object[] {
                        txtFName,
                        txtLName,
                        txtPhoneNo,
                        txtMobileNo,
                        txtEMail,
                        txtAddress,
                        txtUsername,
                        txtCountry,
                        comboUserType});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Create_User_LoginAsync(string txtFName, string txtLName, string txtPhoneNo, string txtMobileNo, string txtEMail, string txtAddress, string txtUsername, string txtCountry, string comboUserType) {
            this.Create_User_LoginAsync(txtFName, txtLName, txtPhoneNo, txtMobileNo, txtEMail, txtAddress, txtUsername, txtCountry, comboUserType, null);
        }
        
        /// <remarks/>
        public void Create_User_LoginAsync(string txtFName, string txtLName, string txtPhoneNo, string txtMobileNo, string txtEMail, string txtAddress, string txtUsername, string txtCountry, string comboUserType, object userState) {
            if ((this.Create_User_LoginOperationCompleted == null)) {
                this.Create_User_LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreate_User_LoginOperationCompleted);
            }
            this.InvokeAsync("Create_User_Login", new object[] {
                        txtFName,
                        txtLName,
                        txtPhoneNo,
                        txtMobileNo,
                        txtEMail,
                        txtAddress,
                        txtUsername,
                        txtCountry,
                        comboUserType}, this.Create_User_LoginOperationCompleted, userState);
        }
        
        private void OnCreate_User_LoginOperationCompleted(object arg) {
            if ((this.Create_User_LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Create_User_LoginCompleted(this, new Create_User_LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void Create_User_LoginCompletedEventHandler(object sender, Create_User_LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Create_User_LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Create_User_LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591